name: Check every midnight

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  deps_audit:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo dependencies security audit
        uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  e2e_debug:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Just command runner
        uses: taiki-e/install-action@just

      - name: Install environment dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-9 cmake libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev protobuf-compiler librocksdb-dev

      - name: Load persistent storage
        run: |
          curl -L https://github.com/witnet/witnet-rust/releases/download/0.5.0-rc1/witnet-rust-testnet-5-tests-storage.tar.gz --output ./storage.tar.gz
          tar -zxf ./storage.tar.gz

      - name: Run debug E2E test
        run: just e2e-debug