name: Check on every push

on: [push, pull_request]

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: 1
      CLIPPY_LINTS: >-
        -D warnings
        -D clippy::cast-lossless
        -D clippy::cast-possible-truncation
        -D clippy::cast-possible-wrap
        -D clippy::cast-precision-loss
        -D clippy::cast-sign-loss
        -D clippy::checked-conversions
        -A clippy::upper-case-acronyms
        -A clippy::uninlined-format-args
      ROCKSDB_INCLUDE_DIR: /usr/local/include
      ROCKSDB_LIB_DIR: /usr/local/lib
      LD_LIBRARY_PATH: /usr/local/lib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ensure some subcrate versions match that of the main crate
      - name: Checking version of node
        uses: ./.github/actions/versions-match
        with:
          subcrate: node

      - name: Checking version of wallet
        uses: ./.github/actions/versions-match  
        with:
          subcrate: wallet

      - name: Checking version of toolkit
        uses: ./.github/actions/versions-match  
        with:
          subcrate: toolkit

      - name: Checking version of data_structures
        uses: ./.github/actions/versions-match
        with:
          subcrate: data_structures

      - name: Checking version of bridges/centralized-ethereum
        uses: ./.github/actions/versions-match
        with:
          subcrate: bridges/centralized-ethereum

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: rustfmt, clippy

      - name: Formatter
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Install compilation system dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-9 cmake libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev protobuf-compiler

      - name: Compile and install RocksDB
        run: |
          git clone https://github.com/facebook/rocksdb.git
          cd rocksdb
          git checkout v8.1.1
          make shared_lib
          sudo make install-shared

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-targets --all-features -- ${{ env.CLIPPY_LINTS }} -A clippy::many-single-char-names

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --verbose

      # This is used to ensure that Cargo.lock is up to date
      - name: Check for unstaged files
        run: git diff --exit-code
